spring:
  application:
    name: "configmanager"
  profiles:
    #active: "native"
    active: "git"
  cloud:
    config:
      server:
        native:
          #search-locations: "file:///${workspace}//broker-infrastructure//configuration"
          #search-locations: "classpath:/config"
        git:
          uri: "https://github.com/jcorderop/broker-configuration.git"
          clone-on-start: true
          default-label: "main"
    compatibility-verifier:
      enabled: false
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 9080

encrypt:
  key: "broker+configuration+manager"

