spring:
  application:
    name: "loadbalancer"
  cloud:
    compatibility-verifier:
      enabled: false

server:
  port: 9082

logging:
  level:
    org:
      springframework: INFO

eureka:
  port: 9082
  instance:
    preferIpAddress: true
    hostname: "localhost"
  client:
    enabled: true
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: "http://${eureka.instance.hostname}:${eureka.port}/eureka/"